name: Deploy to server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Run clone and restart script on server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            set -e
            cd ~/yamao-household-chem-site
            echo '------------------------Copy repo------------------------'
            git pull origin main
            echo '------------------------Switch to Node.js 20------------------------'
            export NVM_DIR="$HOME/.nvm"
            source "$NVM_DIR/nvm.sh"
            nvm use 20
            echo '------------------------Stop web server------------------------'
            pm2 stop server
            echo '------------------------Build frontend------------------------'
            cd ~/yamao-household-chem-site/household-chem-site/frontend
            npm run build
            echo '------------------------Start web server------------------------'
            cd ~/yamao-household-chem-site/household-chem-site/backend
            pm2 start server